name: Interfaces
author: sebwoh
category: Native
tags: [interfaces, oop, interface, class, classes]
requires: core:1.2.4: '*'
#docs: http://wiki.github.com/sebwoh/Mootools-Class-Interfaces
#current: 0.1.1